<?php
/*
*/
?>

<?php get_header(); ?>

<!-- Homepage content -->
<div class="container wn_homepage-content">


        <div class="wn_content_rx">
            
        </div>

        <div class="wn_mwh_rev_slider_wrapper">

            <div class="wn_mwh_hero_slider_bg_img" style="background-image:url('<?php echo wp_get_attachment_image_url(1395, [970, 395]); ?>')">
                <img class="wn_mwh_hero_text_img " src="<?php echo wp_get_attachment_image_url(495, 'large'); ?>" alt="text">
                
                <div class="wn_mwh_hero_link_wrapper">
                    <a class="wn_mwh_hero_links wn_mwh_hero_link_1">LEARN MORE ABOUT PRIMAL DIGESTIVE ENZYMES</a>
                </div> 
            </div>

            <div class="wn_mwh_hero_slider_bg_img" style="display: none; background-image:url('<?php echo wp_get_attachment_image_url(1396, [970, 395]); ?>')">
                <img class="wn_mwh_hero_text_img " src="<?php echo wp_get_attachment_image_url(493, 'large'); ?>" alt="text">

                <div style="transform:translateX(-7%);" class="wn_mwh_hero_link_wrapper">
                    <a class="wn_mwh_hero_links wn_mwh_hero_link_2">DOWNLOAD FREE E-BOOK</a>
                </div> 
                <a class="wn_mwh_" href=""></a>
            </div>

        </div>

        <div class="wn_mwh_wc_products_carousel_wrapper">
            <div class="wn_mwh_header_wrapper">
                <span>FEATURED PRODUCTS</span>
                <div class="wn_mwh_carousel_append_dots">
                    <!-- generated by slick at custom.js -->
                </div>
            </div>

            <div style="display: flex; justify-content: center;" class="wn_mwh_wc_products_carousel">
 
                <?php //wn_products_carousel([], 3, 0); ?>
                <?php wn_products_carousel([], 3, 0); ?>

            </div>
        </div>

        <?php more_post_ajax(); ?>

</div>

<?php get_footer(); ?>